# NumPy for Data Science #


In [1]:
import numpy as np
print(np)

<module 'numpy' from '/home/martin/.local/lib/python3.6/site-packages/numpy/__init__.py'>


In [2]:
a = np.array([6, 7, 8, 9])
print(a)
print(type(a))

[6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([6, 7, 8.0, 9])
print(a)
print(type(a))

In [ ]:
a = np.array([6, '7', 8.0, 9])
print(a)
print(type(a))

In [ ]:
a = np.array([[1, 2], 
              [3, 4]])
print(a)

In [ ]:
zeros_array = np.zeros(5)
print(zeros_array)

In [ ]:
zeros_array = np.zeros((5, 5))
print(zeros_array)

In [ ]:
ones_array = np.ones(5)
print(type(ones_array))
print(ones_array)

In [ ]:
evenly_spaced = np.linspace(0, 20, 5)
print(evenly_spaced)

In [ ]:
x = np.linspace(-1, 1, 11)
print(x)
y = np.sin(x)
print(y)

In [ ]:
print(np.arange(15))
print(np.arange(5, 15))
print(np.arange(0, 15, 4))

In [ ]:
five_by_four = np.arange(20).reshape(5,4)
print(five_by_four)

In [ ]:
print(five_by_four.T)

In [3]:
import pandas as pd
raw_data = pd.read_csv("/home/martin/datasets/flights.csv")
raw_data.head()

year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0  2013      1    1     517.0             515        2.0     830.0   
1  2013      1    1     533.0             529        4.0     850.0   
2  2013      1    1     542.0             540        2.0     923.0   
3  2013      1    1     544.0             545       -1.0    1004.0   
4  2013      1    1     554.0             600       -6.0     812.0   

   sched_arr_time  arr_delay carrier  flight tailnum origin dest  air_time  \
0             819       11.0      UA    1545  N14228    EWR  IAH     227.0   
1             830       20.0      UA    1714  N24211    LGA  IAH     227.0   
2             850       33.0      AA    1141  N619AA    JFK  MIA     160.0   
3            1022      -18.0      B6     725  N804JB    JFK  BQN     183.0   
4             837      -25.0      DL     461  N668DN    LGA  ATL     116.0   

   distance  hour  minute             time_hour  
0      1400     5      15  2013-01-01T05:00:00Z  
1      1416     5      29  2013-01-01T05:00:00Z  
2      1089     5      40  2013-01-01T05:00:00Z  
3      1576     5      45  2013-01-01T05:00:00Z  
4       762     6       0  2013-01-01T06:00:00Z

In [5]:
data = raw_data.to_numpy()
print(data)

[[2013 1 1 ... 5 15 '2013-01-01T05:00:00Z']
 [2013 1 1 ... 5 29 '2013-01-01T05:00:00Z']
 [2013 1 1 ... 5 40 '2013-01-01T05:00:00Z']
 ...
 [2013 9 30 ... 12 10 '2013-09-30T12:00:00Z']
 [2013 9 30 ... 11 59 '2013-09-30T11:00:00Z']
 [2013 9 30 ... 8 40 '2013-09-30T08:00:00Z']]


In [ ]:
print('data.shape: {}'.format(data.shape))

In [ ]:
print('data.size: {}'.format(data.size))

In [ ]:
print('data.ndim: {}'.format(data.ndim))

In [ ]:
dep_time = data[:, 4]
print(dep_time)
print(type(dep_time))

In [6]:
dep_time = data[:5, 3:6]
print(dep_time)

[[517.0 515 2.0]
 [533.0 529 4.0]
 [542.0 540 2.0]
 [544.0 545 -1.0]
 [554.0 600 -6.0]]


In [8]:
dep_delay = data[:500, 5]
print('Sum: {}'.format(dep_delay.sum()))
print('Min: {}'.format(dep_delay.min()))
print('Max: {}'.format(dep_delay.max()))
print('Ave: {}'.format(dep_delay.mean()))

Sum: 2955.0
Min: -15.0
Max: 853.0
Ave: 5.91


In [10]:
dep_delay_hours = data[:500, 5] / 60
print('Sum: {}'.format(dep_delay_hours.sum()))
print('Min: {}'.format(dep_delay_hours.min()))
print('Max: {}'.format(dep_delay_hours.max()))
print('Ave: {}'.format(dep_delay_hours.mean()))

Sum: 49.24999999999999
Min: -0.25
Max: 14.216666666666667
Ave: 0.09849999999999999


In [ ]:
print('Standard Deviation: {}'.format(dep_delay_hours.std()))
print('Variance: {}'.format(dep_delay_hours.var()))

In [11]:
print(dep_delay_hours > 1)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False Fa

In [12]:
print(dep_delay_hours[dep_delay_hours > 1])

[1.6833333333333333 1.1833333333333333 14.216666666666667 2.4
 2.2333333333333334 1.6 1.1833333333333333 1.2833333333333334
 1.1666666666666667 1.9166666666666667 1.75 2.033333333333333
 1.4666666666666666 1.0666666666666667]


Numpy Documentation: https://docs.scipy.org/doc/numpy/reference/index.html