# NumPy for Data Science #


In [5]:
import numpy as np
print(np)

<module 'numpy' from '/home/martin/.local/lib/python3.6/site-packages/numpy/__init__.py'>


In [15]:
a = np.array([6, 7, 8, 9])
print(a)
print(type(a))

[6 7 8 9]
<class 'numpy.ndarray'>


In [16]:
zeros_array = np.zeros(5)
print(type(zeros_array))
print(zeros_array)

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]


In [11]:
ones_array = np.ones(5)
print('Type: {}'.format(type(ones_array)))
print(ones_array)

Type: <class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


Notice that in both of these cases the items within the NumPy array have decimal places. This suggests that the data types of the individual items are floats. Lets check to be sure

In [18]:
zeros_array = np.zeros(5)
print(type(zeros_array[0]))
ones_array = np.ones(5)
print(type(ones_array[0]))

<class 'numpy.float64'>
<class 'numpy.float64'>


As we suspected, the individual items were infact, floats.

Numpy Arrays are handy for dealing with data sets that are multi dimmensional. Here we are creating a two dimmensional array.  

In [24]:
two_dimmensions = np.array([np.zeros(5), np.ones(5)])
print('Two Dimmensional Array:\n{}\n'.format(two_dimmensions))
print('Shape of Two Dimmensional Array:\n{}'.format(two_dimmensions.shape))

Two Dimmensional Array:
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]

Shape of Two Dimmensional Array:
(2, 5)


In [25]:
two_dimmensions.shape = (5, 2)
print('Two Dimmensional Array:\n{}\n'.format(two_dimmensions))

Two Dimmensional Array:
[[0. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 1.]]



In [ ]:
with open('flights.csv', 'r') as f:
    for n, line in enumerate(f.readlines()):
        if n > 5:
            break
        print(line)

This is great! We can read in the data from a file and manipulate it. Let's take a look at how we might do this.

In [ ]:
data = []
with open('flights.csv', 'r') as f:
    for n, line in enumerate(f.readlines()):
        if n > 5:
            break
        if n == 0:
            header = line.split(',')
            for i, title in enumerate(header):
                print(i, title)
        else:
            separated = line.split(',')
            data.append(separated)
            print(separated)

So we could pull i